### ISSUE TITLE
Doesn't run on Xcode 7.0.1

### ISSUE THREAD

**Issue by lumierephoto** [hawkfalcon/SpaceEvaders#7]
Lot's of Swift compiler errors. 

Any easy way to fix? Or not?

**Comment by hawkfalcon** [comment]
I'll update it soon.

**Comment by lumierephoto** [comment]
Cool!

**Comment by hawkfalcon** [comment]
Fixed with https://github.com/hawkfalcon/SpaceEvaders/commit/eba49c3b0e8652c4d2b3628fa5e68ba569023a90

**Comment by lumierephoto** [comment]
Awesome. That was fast.
