### ISSUE TITLE
App Store clone

### ISSUE THREAD

**Issue by QuetzalPretzel** [hawkfalcon/SpaceEvaders#8]
Hi Tristen,

I'm sorry to report that your app has been cloned :-(

See here: https://itunes.apple.com/us/app/asteroid-evaders/id972272888?mt=8

He is actually a serial cloner registered on GitHub here: https://github.com/michaeldugan

Good news, you can get his app pulled by contacting Apple Legal here:

http://www.apple.com/legal/internet-services/itunes/appstorenotices/

Let me know if you need any advice on submitting the claim, it helps to include your app id in the text  and add that you icon have been infringed and even the name has been unaltered in the game/screenshots (don't be afraid to write lots even though the text entry box is tiny).

**Comment by hawkfalcon** [comment]
Fun, thanks. Imitation is the best form of flattery, I suppose.

**Comment by michaeldugan** [comment]
@hawkfalcon Do you want me to remove the app?

**Comment by hawkfalcon** [comment]
@michaeldugan it has an MIT license, so I can't really stop you. However, I do challenge you to create your own unique game in swift, rather than just cloning other's hard work and submitting it as your own. It doesn't look like any of the apps you've put on the app store are your own (or are just slight modifications to apps). Be creative. Learn. Think before you steal.

**Comment by QuetzalPretzel** [comment]
@hawkfalcon its your choice, but given there are no modifications, identical code, identical icon, identical name inside the app, you have full grounds to issue a take down request.  Developers should not do that in the App Store regardless of the licence.

**Comment by hawkfalcon** [comment]
@QuetzalPretzel that is true. Thank you. Okay, @michaeldugan I'll give you 3 days to remove the app from the app store, and after that if it is not removed I will contact Apple.
